apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: api
          image: three-tier-api
          imagePullPolicy: Never
          ports:
            - containerPort: 5001
          env:
            - name: MYSQL_HOST
              value: mysql
            - name: MYSQL_USER
              value: appuser
            - name: MYSQL_PASSWORD
              value: app_password
            - name: MYSQL_DB
              value: quotesdb
---
apiVersion: v1
kind: Service
metadata:
  name: api
spec:
  selector:
    app: api
  ports:
    - port: 5001
      targetPort: 5001
